version: '3'

services:
  postgres:
    image: 'postgres:14.3'
    container_name: dashboard-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coursework
    restart: unless-stopped

  app:
    build: .
    container_name: dashboard-rest
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=coursework
    restart: "on-failure"

volumes:
  postgres-data: